### ISSUE TITLE
hiragana transcription error

### ISSUE THREAD

**Issue by hisakonog** [betaflag/kanji-review-app#3]
Hi Nick I am Gina's friend, I played your Kanji review and I found an error for you: 
神道
しんと
god way

it is not "shinto" but "shintoo" 
pronunciation is long "o" but in hiragana しんとう 
I am learning Backbone that's why I looked at your repository. 
kanji review is cute, it's a good self-drill.

**Comment by ghost** [comment]
Thank you very much, I knew we did some typos when filling the kanji but it's hard to find them once they are in. It will be fixed soon.
